@startuml
skinparam dpi 100

actor "用户" as User
participant "古树检索界面" as Page
participant "TreeRetrieveController" as Controller
participant "ITreeRetrieveService" as Service
participant "TreeRetrieveMapper" as Mapper

User -> Page: 访问古木检索界面
Page -> Controller: 调用/tree/getTreeInfo接口
Controller -> Service: 调用getTreeInfoByMultiModel方法
Service -> Mapper: 调用selectTreeInfoByMultiModel方法
Mapper --> Service: 返回古木检索信息
Service --> Controller: 返回古木检索信息
Controller --> Page: 返回古木检索信息
Page --> User: 检索失败/检索成功返古木检索信息


@enduml