@startuml
skinparam dpi 100

actor "用户" as User
participant "登录注册页" as LoginPage
participant "用户信息页" as Page
participant "UserController" as Controller
participant "IUserService" as Service
participant "UserMapper" as Mapper

User -> LoginPage: 访问登录注册页面
LoginPage --> User: 未登录/过期请重新登陆
LoginPage -> Page: 查询用户信息
Page -> Controller: 调用/user/getUserInfo接口
Controller -> Service: 调用getUserInfoByUserId方法
Service -> Mapper: 调用selectUserInfoByUserId方法
Mapper --> Service: 返回用户信息
Service --> Controller: 返回用户信息
Controller --> Page: 返回用户信息
Page --> User: 登录失败/登录成功返回用户信息

@enduml