server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wiki-dev?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: r-uf6ljbcdaxobsifyctpd.redis.rds.aliyuncs.com
    password: Redis000
    port: 6379


logging:
  level:
    com:
      jiawa:
        wiki:
          mapper: trace

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

test:
  hello: Hello1
