GET http://localhost:8880/hello;

###
POST http://localhost:8880/hello/post
Content-Type: application/x-www-form-urlencoded

name=world

###
GET http://localhost:8880/test/hello;


###

GET http://localhost:8880/test/redis/set/test123/test
Accept: application/json

###

GET http://localhost:8880/redis/get/185302205295890432
Accept: application/json

###