server{
  listen 80;
  # 前端nginx配置
  # server_name 101.201.154.144;
  server_name wiki.laosonga.com;

  location / {
    alias /root/web/;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

}
