@startuml
'https://plantuml.com/use-case-diagram
skinparam dpi 200

left to right direction
actor 普通用户  #line.bold
actor 系统管理员 #line.bold

usecase 输入文本或图像 as 输入文本或图像 #line.bold
usecase 输出图文 as 输出图文 #line.bold


普通用户 --> 输入文本或图像
系统管理员 --> 输入文本或图像
输入文本或图像 ..> 输出图文:<<包含>>


@enduml