@startuml
'https://plantuml.com/use-case-diagram
skinparam dpi 200

left to right direction
actor 系统管理员 #line.bold

usecase 个人信息 as 个人信息 #line.bold

usecase 修改头像 as 修改头像 #line.bold
usecase 修改密码 as 修改密码 #line.bold
usecase 修改性别 as 修改性别 #line.bold
usecase 修改年龄 as 修改年龄 #line.bold

系统管理员 --> 个人信息

个人信息 ..> 修改头像:<<包含>>
个人信息 ..> 修改密码:<<包含>>
个人信息 ..> 修改性别:<<包含>>
个人信息 ..> 修改年龄:<<包含>>

@enduml